//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zekotec01.DALMssql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cihaz
    {
        public int Id { get; set; }
        public string Ip { get; set; }
        public int Port { get; set; }
        public string Adi { get; set; }
        public int CihazTipi { get; set; }
    }
}
