//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zekotec01.DALMssql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Izin = new HashSet<Izin>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CihazUserId { get; set; }
        public string AdSoyad { get; set; }
        public string CepTel { get; set; }
        public string AileTel { get; set; }
        public byte[] Resim { get; set; }
        public Nullable<int> Durum { get; set; }
        public string TcKimlik { get; set; }
        public string OdaNo { get; set; }
        public string Adres { get; set; }
        public string Not { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izin> Izin { get; set; }
    }
}
