//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zekotec01.DALMssql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YoklamaDbEntities : DbContext
    {
        public YoklamaDbEntities()
            : base("name=YoklamaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cihaz> Cihaz { get; set; }
        public virtual DbSet<Izin> Izin { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<OkumaKayit> OkumaKayit { get; set; }
        public virtual DbSet<YoklamaZamani> YoklamaZamani { get; set; }
    }
}
