//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zekotec01.DALMssql
{
    using System;
    using System.Collections.Generic;
    
    public partial class YoklamaZamani
    {
        public int Id { get; set; }
        public System.DateTime BaslamaSaati { get; set; }
        public System.DateTime BitisSaati { get; set; }
        public int Sure { get; set; }
        public int Dakika { get; set; }

      

    }
}
